//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinusForumTipsDesktop.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class ChangeLogInfo : global::System.Configuration.ApplicationSettingsBase {
        
        private static ChangeLogInfo defaultInstance = ((ChangeLogInfo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ChangeLogInfo())));
        
        public static ChangeLogInfo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseNotes {
            get {
                return ((string)(this["ReleaseNotes"]));
            }
            set {
                this["ReleaseNotes"] = value;
            }
        }
    }
}
