//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinusForumTipsDesktop.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class URLs : global::System.Configuration.ApplicationSettingsBase {
        
        private static URLs defaultInstance = ((URLs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new URLs())));
        
        public static URLs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/LinusForumTips/LinusForumTipsDesktop/master/lic" +
            "ense-localization/license_korean.md")]
        public string koreanLicenseURL {
            get {
                return ((string)(this["koreanLicenseURL"]));
            }
            set {
                this["koreanLicenseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/LinusForumTips/LinusForumTipsDesktop/blob/master/license.md")]
        public string englishLicenseURL {
            get {
                return ((string)(this["englishLicenseURL"]));
            }
            set {
                this["englishLicenseURL"] = value;
            }
        }
    }
}
