//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinusForumTipsDesktop.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class URLs : global::System.Configuration.ApplicationSettingsBase {
        
        private static URLs defaultInstance = ((URLs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new URLs())));
        
        public static URLs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/LinusForumTips/LinusForumTipsDesktop/issues/")]
        public string BugReportURL {
            get {
                return ((string)(this["BugReportURL"]));
            }
            set {
                this["BugReportURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/LinusForumTips/LinusForumTipsDesktop/releases/")]
        public string CheckForUpdatesURL {
            get {
                return ((string)(this["CheckForUpdatesURL"]));
            }
            set {
                this["CheckForUpdatesURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/AluminiumTech/LinusForumTips/LinusForumTipsDesktop/")]
        public string StartPage {
            get {
                return ((string)(this["StartPage"]));
            }
            set {
                this["StartPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/LinusForumTips/LinusForumTipsDesktop/wiki/")]
        public string wikiURL {
            get {
                return ((string)(this["wikiURL"]));
            }
            set {
                this["wikiURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://raw.githubusercontent.com/LinusForumTips/LinusForumTipsDesktop/master/lic" +
            "ense.md")]
        public string licenseURL_English {
            get {
                return ((string)(this["licenseURL_English"]));
            }
            set {
                this["licenseURL_English"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.github.com/AluminiumTech/LithiumClassic/")]
        public string lithiumClassicPage {
            get {
                return ((string)(this["lithiumClassicPage"]));
            }
            set {
                this["lithiumClassicPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/LinusForumTips/LinusForumTipsDesktop/blob/master/README.md")]
        public string readme_English {
            get {
                return ((string)(this["readme_English"]));
            }
            set {
                this["readme_English"] = value;
            }
        }
    }
}
