//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinusForumTipsDesktop.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Versions : global::System.Configuration.ApplicationSettingsBase {
        
        private static Versions defaultInstance = ((Versions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Versions())));
        
        public static Versions Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alpha 1.12.0")]
        public string AluminiumCore {
            get {
                return ((string)(this["AluminiumCore"]));
            }
            set {
                this["AluminiumCore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("March 24th 2017")]
        public string BuildDate {
            get {
                return ((string)(this["BuildDate"]));
            }
            set {
                this["BuildDate"] = value;
            }
        }
    }
}
